### ISSUE TITLE
Task cancellation can fail, causing execution to crash

### ISSUE THREAD

**Issue by MathiasStokholm** [MathiasStokholm/alkymi#38]
In some cases (Python 3.8), execution can fail with the following error:
```
Traceback (most recent call last):
  File "/home/developer/vsts-agent/_work/5/s/lightcrafter_verification/scripts/verify.py", line 182, in <module>
    main()
  File "/home/developer/vsts-agent/_work/5/s/lightcrafter_verification/scripts/verify.py", line 178, in main
    lab.open()
  File "/home/developer/.local/lib/python3.8/site-packages/alkymi/lab.py", line 226, in open
    self.brew(recipe, jobs=parsed_args.jobs, progress_type=parsed_args.progress)
  File "/home/developer/.local/lib/python3.8/site-packages/alkymi/lab.py", line 86, in brew
    return _call_brew(recipe)
  File "/home/developer/.local/lib/python3.8/site-packages/alkymi/lab.py", line 77, in _call_brew
    return _recipe.brew(jobs=jobs, progress_type=progress_type)
  File "/home/developer/.local/lib/python3.8/site-packages/alkymi/recipe.py", line 107, in brew
    return brew(self, jobs=jobs, progress_type=progress_type)
  File "/home/developer/.local/lib/python3.8/site-packages/alkymi/core.py", line 437, in brew
    result, _ = evaluate_recipe(recipe, graph, statuses, jobs, progress_type)
  File "/home/developer/.local/lib/python3.8/site-packages/alkymi/core.py", line 383, in evaluate_recipe
    output, checksum = loop.run_until_complete(_execute())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/developer/.local/lib/python3.8/site-packages/alkymi/core.py", line 376, in _execute
    coro_or_task.close()
AttributeError: '_asyncio.Task' object has no attribute 'close'
```

Apparently, a `_asyncio.Task` is not an instance of `asyncio.Task`

**Comment by MathiasStokholm** [comment]
Fixed in v0.2.1.
